# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('users', models.ManyToManyField(related_name='interests', to='login_reg_app.User')),
            ],
        ),
    ]
